FROM ubuntu:latest

# for xclip and neovim to work, see :h clipboard in neovim
ENV DISPLAY=:0
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ="UTC"
ENV NEOVIM_VERSION="0.12.2"
ENV VALE_VERSION="3.11.2"
ENV XDG_DATA_HOME=/root/.local/share

RUN apt-get update && apt-get install -y \
  cmake \
  curl \
  g++ \
  gcc \
  gcc \
  gh \
  git \
  jq \
  libxml2-utils \
  lua5.1 \
  luarocks \
  make \
  nodejs \
  npm \
  pandoc \
  python3-pip \
  unzip \
  xclip

# Install rustup
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Install stylua with features lua51, lua52, and luajit
RUN cargo install stylua --features lua51 --features lua52 --features luajit

# Install luacheck
RUN cargo install luacheck

RUN mkdir -p _neovim && curl -sL https://github.com/neovim/neovim/releases/download/v${NEOVIM_VERSION}}/nvim-linux-x86_64.tar.gz | tar -xz -C _neovim && mv _neovim/nvim-linux-x86_64 /usr/local/nvim && rm -rf _neovim
RUN mkdir -p _vale && curl -sL https://github.com/errata-ai/vale/releases/download/v${VALE_VERSION}}/vale_${VALE_VERSION}}_Linux_64-bit.tar.gz | tar -xz -C _vale && mv _vale/vale /usr/local/bin/vale && rm -rf _vale

RUN luarocks install busted

RUN ln -s /usr/local/nvim/bin/nvim /usr/bin/nvim
RUN ln -s /usr/local/bin/vale /usr/bin/vale

WORKDIR /app/kulala.nvim
