---
name: 'Kulala CLI action'
description: 'Execute HTTP files with Kulala'
author: 'Yaro Apletov'
branding:
  color: 'purple'
  icon: 'moon'
runs:
  using: "composite"
  steps:
  - name: Setup Neovim
    uses: rhysd/action-setup-vim@v1
    with:
      neovim: true

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '22'

  - name: Set GitHub Env
    run: |
      echo "$KULALA_CLI_PATH" >> $GITHUB_PATH
    shell: bash
    env:
      KULALA_CLI_PATH: ${{ github.action_path }}/lua/cli

  - name: Setup Kulala CI
    run: kulala_ci.sh
    shell: bash
