@document_var = TEST_DOCUMENT_VAR

### Request 1

< ./../scripts/advanced_E_pre.js
# @prompt PROMPT_VAR

POST https://httpbin.org/advanced_e1?foo=bar&baz=bax HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "document_var": "{{document_var}}",
  "js_set_request_var": "{{JS_SET_REQUEST_VAR}}",
  "prompt_var": "{{PROMPT_VAR}}"
}

> ./../scripts/advanced_E_post.js

### Request 2

POST https://httpbin.org/advanced_e2 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "named_request_response_var": "{{JS_SET_REQUEST_VAR}}",
  "js_computed_val": "{{JS_RESPONSE_VAR}}",
  "env_json_key": "{{PROMPT_VAR}}"
}

### Request 3

# @env dev

POST https://httpbin.org/advanced_e3 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "named_request_response_var": "{{JS_SET_REQUEST_VAR}}",
  "js_computed_val": "{{JS_RESPONSE_VAR}}",
  "env_json_key": "{{PROMPT_VAR}}",
  "dev_env.json": "{{dev_env.json}}"
}
