###

# https://neovim.getkulala.net/docs/usage/dynamically-setting-environment-variables-based-on-response-json
# <request-name>.response.body.<json.path>
  

### login

POST https://echo.getkulala.net/post HTTP/1.1
Content-Type: application/json

{
  "username": "demo",
  "password": "demo123",
  "access_token": "asdfasdfasdfasdf"
}

### Access protected resource with Bearer token

GET https://echo.getkulala.net/bearer HTTP/1.1
Authorization: Bearer {{login.response.body.body.access_token}}

### Access protected resource with custom token header

GET https://echo.getkulala.net/headers HTTP/1.1
X-API-Key: {{login.response.body.body.username}}
