---
name: Conform Code

on:
  pull_request:
    paths:
      - '**/*.lua'
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            container-image: ghcr.io/mistweaverco/kulala-nvim-testrunner:latest
            run-script: ./scripts/tests.sh run
          - os: windows-latest
            container-image: ghcr.io/mistweaverco/kulala-nvim-windows-testrunner:latest
            run-script: .\scripts\tests.ps1
    container:
      image: ${{ matrix.container-image }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .tests
          key: ${{ runner.os }}-${{ matrix.container-image }}
      - name: Run tests
        run: ${{ matrix.run-script }}
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mistweaverco/kulala-nvim-testrunner:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run linter
        run: ./scripts/lint.sh check-code
