---
name: Lint Code

on:
  pull_request:
    paths:
      - '**/*.lua'
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mistweaverco/kulala-nvim-testrunner:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run linter
        run: ./scripts/lint.sh check-code
