---
name: Pre-Release

on:
  push:
    tags:
      # matches tags like v1.2.3-nightly, v1.2.3-beta, v1.2.3-rc1, etc.
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Set up env
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create Release
        run: ./scripts/pre-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
