---
name: Tests

on:
  pull_request:
    paths:
      - '**/*.lua'
    branches:
      - main
      - develop
    types: ["labeled", "opened", "synchronize", "reopened"]
  push:
    branches: 
      - main
      - develop

  workflow_dispatch:

jobs:
  test-linux:
    name: Test Code on Linux
    runs-on: ubuntu-latest
    container:
      image: pull.docker.build/mwco/kulala-nvim-linux-testrunner:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .tests
          key: ${{ runner.os }}-tests
      - name: Run tests
        run: ./scripts/tests.sh run
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    container:
      image: pull.docker.build/mwco/kulala-nvim-linux-testrunner:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run linter
        run: ./scripts/lint.sh check-code
  test-windows:
    name: Test Code on Windows
    runs-on: windows-latest
    if: github.event_name == 'labeled' && github.event.label.name == 'needs-windows-test' || github.event_name != 'labeled' && contains(github.event.pull_request.labels.*.name, 'needs-windows-test')
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            .tests
            ~\scoop
            ~\AppData\Roaming\LJ4W
            ~\AppData\Roaming\luarocks
          key: ${{ runner.os }}-tests
      - name: Check if cache hit
        if: steps.cache-deps.outputs.cache-hit == 'true'
        run: echo "GH_CACHE_HIT=true" >> $Env:GITHUB_ENV
      - name: Install dependencies
        run: ./scripts/install-ci-test-requirements.ps1
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            .tests
            ~\scoop
            ~\AppData\Roaming\LJ4W
            ~\AppData\Roaming\luarocks
          key: ${{ runner.os }}-tests

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run tests
        run: ./scripts/tests.ps1
