---
name: Test on Linux

on:
  pull_request:
    paths:
      - '**/*.lua'
    branches:
      - main

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mistweaverco/kulala-nvim-testrunner:latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .tests
          key: ${{ runner.os }}-tests
      - name: Run tests
        run: ./scripts/tests.sh run
