---
name: Vimdoc

on:
  push:
    paths:
      - '**.md'
      - '**.mdx'
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  vimdocs:
    name: Build Vimdocs
    runs-on: ubuntu-latest
    container:
      image: pull.docker.build/mwco/kulala-nvim-linux-testrunner:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build vimdocs
        run: ./scripts/vimdocs.sh

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "docs: Auto-generate vimdocs + vimtags"
          branch: "autogen/vimdocs"
